#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

// #define FOREACH_TM(F) \
//     F(FOCUS_PUNCH) \
//     F(DRAGON_CLAW) \
//     F(WATER_PULSE) \
//     F(CALM_MIND) \
//     F(ROAR) \
//     F(TOXIC) \
//     F(HAIL) \
//     F(BULK_UP) \
//     F(BULLET_SEED) \
//     F(HIDDEN_POWER) \
//     F(SUNNY_DAY) \
//     F(TAUNT) \
//     F(ICE_BEAM) \
//     F(BLIZZARD) \
//     F(HYPER_BEAM) \
//     F(LIGHT_SCREEN) \
//     F(PROTECT) \
//     F(RAIN_DANCE) \
//     F(GIGA_DRAIN) \
//     F(SAFEGUARD) \
//     F(FRUSTRATION) \
//     F(SOLAR_BEAM) \
//     F(IRON_TAIL) \
//     F(THUNDERBOLT) \
//     F(THUNDER) \
//     F(EARTHQUAKE) \
//     F(RETURN) \
//     F(DIG) \
//     F(PSYCHIC) \
//     F(SHADOW_BALL) \
//     F(BRICK_BREAK) \
//     F(DOUBLE_TEAM) \
//     F(REFLECT) \
//     F(SHOCK_WAVE) \
//     F(FLAMETHROWER) \
//     F(SLUDGE_BOMB) \
//     F(SANDSTORM) \
//     F(FIRE_BLAST) \
//     F(ROCK_TOMB) \
//     F(AERIAL_ACE) \
//     F(TORMENT) \
//     F(FACADE) \
//     F(SECRET_POWER) \
//     F(REST) \
//     F(ATTRACT) \
//     F(THIEF) \
//     F(STEEL_WING) \
//     F(SKILL_SWAP) \
//     F(SNATCH) \
//     F(OVERHEAT)

#define FOREACH_TM(F) \
F(WORK_UP) \
F(DRAGON_CLAW) \
F(PSYSHOCK) \
F(CALM_MIND) \
F(ROAR) \
F(TOXIC) \
F(FAKE_OUT) \
F(BULK_UP) \
F(VENOSHOCK) \
F(HIDDEN_POWER) \
F(SUNNY_DAY) \
F(TAUNT) \
F(ICE_BEAM) \
F(BLIZZARD) \
F(HYPER_BEAM) \
F(LIGHT_SCREEN) \
F(PROTECT) \
F(RAIN_DANCE) \
F(ROOST) \
F(SAFEGUARD) \
F(FRUSTRATION) \
F(SOLAR_BEAM) \
F(SMACK_DOWN) \
F(THUNDERBOLT) \
F(THUNDER) \
F(EARTHQUAKE) \
F(RETURN) \
F(LEECH_LIFE) \
F(PSYCHIC) \
F(SHADOW_BALL) \
F(BRICK_BREAK) \
F(DOUBLE_TEAM) \
F(REFLECT) \
F(SLUDGE_WAVE) \
F(FLAMETHROWER) \
F(SLUDGE_BOMB) \
F(SANDSTORM) \
F(FIRE_BLAST) \
F(ROCK_TOMB) \
F(AERIAL_ACE) \
F(TORMENT) \
F(FACADE) \
F(FLAME_CHARGE) \
F(REST) \
F(ATTRACT) \
F(THIEF) \
F(LOW_SWEEP) \
F(ROUND) \
F(ECHOED_VOICE) \
F(OVERHEAT) \
F(STEEL_WING) \
F(FOCUS_BLAST) \
F(ENERGY_BALL) \
F(FALSE_SWIPE) \
F(SCALD) \
F(FLING) \
F(CHARGE_BEAM) \
F(SKY_DROP) \
F(BRUTAL_SWING) \
F(QUASH) \
F(WILL_O_WISP) \
F(ACROBATICS) \
F(EMBARGO) \
F(EXPLOSION) \
F(SHADOW_CLAW) \
F(PAYBACK) \
F(SMART_STRIKE) \
F(GIGA_IMPACT) \
F(ROCK_POLISH) \
F(AURORA_VEIL) \
F(STONE_EDGE) \
F(VOLT_SWITCH) \
F(THUNDER_WAVE) \
F(GYRO_BALL) \
F(SWORDS_DANCE) \
F(TRAILBLAZE) \
F(PSYCH_UP) \
F(BULLDOZE) \
F(FROST_BREATH) \
F(ROCK_SLIDE) \
F(X_SCISSOR) \
F(DRAGON_TAIL) \
F(INFESTATION) \
F(POISON_JAB) \
F(DREAM_EATER) \
F(GRASS_KNOT) \
F(SWAGGER) \
F(SLEEP_TALK) \
F(U_TURN) \
F(SUBSTITUTE) \
F(FLASH_CANNON) \
F(TRICK_ROOM) \
F(WILD_CHARGE) \
F(PSYCHIC_FANGS) \
F(SNARL) \
F(NATURE_POWER) \
F(DARK_PULSE) \
F(HAZE) \
F(DAZZLING_GLEAM) \
F(CONFIDE) \
F(CLOSE_COMBAT) \
F(FLARE_BLITZ) \
F(CHARM) \
F(ICE_PUNCH) \
F(SPIKES) \
F(CONFUSE_RAY) \
F(STEALTH_ROCK) \
F(POISON_TAIL) \
F(BLAST_BURN) \
F(TAKE_DOWN) \
F(HEAVY_SLAM) \
F(SWIFT) \
F(THROAT_CHOP) \
F(FEATHER_DANCE) \
F(WATER_PULSE) \
F(FLY) \
F(TRICK) \
F(PSYCHIC_TERRAIN) \
F(BATON_PASS) \
F(UPROAR) \
F(GRAVITY) \
F(BURNING_JEALOUSY) \
F(DRAGON_DANCE) \
F(MISTY_EXPLOSION) \
F(GRASS_PLEDGE) \
F(TRIPLE_AXEL) \
F(GRASSY_GLIDE) \
F(ALLURING_VOICE) \
F(ICE_SPINNER) \
F(WHIRLPOOL) \
F(BRAVE_BIRD) \
F(STEEL_BEAM) \
F(HEAT_WAVE) \
F(ICE_FANG) \
F(SOLAR_BLADE) \
F(FOCUS_PUNCH) \
F(SNOWSCAPE) \
F(AMNESIA) \
F(SCORCHING_SANDS) \
F(SURF) \
F(ACID_SPRAY) \
F(HYDRO_PUMP) \
F(HYDRO_CANNON) \
F(DRACO_METEOR) \
F(METRONOME) \
F(POUNCE) \
F(CRUNCH) \
F(HYPER_VOICE) \
F(DRAGON_CHEER) \
F(SPITE) \
F(MUD_SHOT) \
F(TEMPER_FLARE) \
F(LUNGE) \
F(DUAL_WINGBEAT) \
F(ENDEAVOR) \
F(IMPRISON) \
F(FIRE_FANG) \
F(IRON_HEAD) \
F(THUNDER_FANG) \
F(AGILITY) \
F(ROCK_BLAST) \
F(HEAT_CRASH) \
F(SKITTER_SMACK) \
F(LOW_KICK) \
F(ELECTRIC_TERRAIN) \
F(DISARMING_VOICE) \
F(CHILLING_WATER) \
F(PLAY_ROUGH) \
F(WATERFALL) \
F(NASTY_PLOT) \
F(UPPER_HAND) \
F(GIGA_DRAIN) \
F(TOXIC_SPIKES) \
F(DRAGON_PULSE) \
F(SCALE_SHOT) \
F(SAND_TOMB) \
F(AIR_SLASH) \
F(PSYCHIC_NOISE) \
F(ELECTROWEB) \
F(FIRE_PLEDGE) \
F(MAGICAL_LEAF) \
F(DOUBLE_EDGE) \
F(IRON_DEFENSE) \
F(BUG_BUZZ) \
F(CURSE) \
F(MUDDY_WATER) \
F(BREAKING_SWIPE) \
F(BODY_PRESS) \
F(POWER_GEM) \
F(STORED_POWER) \
F(AURA_SPHERE) \
F(REVERSAL) \
F(ENCORE) \
F(KNOCK_OFF) \
F(ZEN_HEADBUTT) \
F(FIRE_PUNCH) \
F(FOUL_PLAY) \
F(MUD_SLAP) \
F(COACHING) \
F(EXPANDING_FORCE) \
F(POLLEN_PUFF) \
F(POLTERGEIST) \
F(BODY_SLAM) \
F(CHARGE) \
F(STRUGGLE_BUG) \
F(TERA_BLAST) \
F(HIGH_HORSEPOWER) \
F(BUG_BITE) \
F(SUPER_FANG) \
F(HELPING_HAND) \
F(STOMPING_TANTRUM) \
F(DIG) \
F(GRASSY_TERRAIN) \
F(NIGHT_SHADE) \
F(LIQUIDATION) \
F(FAKE_TEARS) \
F(ICY_WIND) \
F(HURRICANE) \
F(FIRE_SPIN) \
F(SCARY_FACE) \
F(SUPERCELL_SLAM) \
F(WEATHER_BALL) \
F(LASH_OUT) \
F(ENDURE) \
F(THUNDER_PUNCH) \
F(ICICLE_SPEAR) \
F(BULLET_SEED) \
F(METAL_SOUND) \
F(SKILL_SWAP) \
F(PETAL_BLIZZARD) \
F(WATER_PLEDGE) \
F(OUTRAGE) \
F(PSYBEAM) \
F(TAILWIND) \
F(MISTY_TERRAIN) \
F(METEOR_BEAM) \
F(PHANTOM_FORCE) \
F(EARTH_POWER) \
F(DRAIN_PUNCH) \
F(EERIE_IMPULSE) \
F(FRENZY_PLANT) \
F(LEAF_STORM) \
F(DRILL_RUN) \
F(DRAINING_KISS) \
F(HARD_PRESS) \
F(HEX) \
F(SEED_BOMB) \
F(GUNK_SHOT) \
F(PAIN_SPLIT) \
F(ELECTRO_BALL) \
F(METAL_CLAW) \
F(AIR_CUTTER) \
F(VACUUM_WAVE) \
F(FLIP_TURN) \
F(FUTURE_SIGHT) \
F(AVALANCHE) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif