LegendChallengeLobby_MapScripts::
	.byte 0

LegendChallengeLobby_EventScripts_MewPC::
	goto EventScript_PC
	releaseall
	end

LegendChallengeLobby_EventScripts_Mewtwo::
	lock
	bufferspeciesname 0, SPECIES_MEWTWO
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_MEWTWO, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Hooh::
	lock
	bufferspeciesname 0, SPECIES_HO_OH
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_HO_OH, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Lugia::
	lock
	bufferspeciesname 0, SPECIES_LUGIA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_LUGIA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Groudon::
	lock
	bufferspeciesname 0, SPECIES_GROUDON
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_GROUDON, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Kyogre::
	lock
	bufferspeciesname 0, SPECIES_KYOGRE
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_KYOGRE, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Rayquaza::
	lock
	bufferspeciesname 0, SPECIES_RAYQUAZA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_RAYQUAZA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Deoxys::
	lock
	bufferspeciesname 0, SPECIES_DEOXYS
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_DEOXYS, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Dialga::
	lock
	bufferspeciesname 0, SPECIES_DIALGA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_DIALGA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Palkia::
	lock
	bufferspeciesname 0, SPECIES_PALKIA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_PALKIA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Giratina::
	lock
	bufferspeciesname 0, SPECIES_GIRATINA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_GIRATINA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Regigigas::
	lock
	bufferspeciesname 0, SPECIES_REGIGIGAS
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_REGIGIGAS, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Arceus::
	lock
	bufferspeciesname 0, SPECIES_ARCEUS
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ARCEUS, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Reshiram::
	lock
	bufferspeciesname 0, SPECIES_RESHIRAM
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_RESHIRAM, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Zekrom::
	lock
	bufferspeciesname 0, SPECIES_ZEKROM
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ZEKROM, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Kyurem::
	lock
	bufferspeciesname 0, SPECIES_KYUREM
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_KYUREM, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Xerneas::
	lock
	bufferspeciesname 0, SPECIES_XERNEAS
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_XERNEAS, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Yveltal::
	lock
	bufferspeciesname 0, SPECIES_YVELTAL
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_YVELTAL, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Zygarde::
	lock
	bufferspeciesname 0, SPECIES_ZYGARDE
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ZYGARDE, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Solgaleo::
	lock
	bufferspeciesname 0, SPECIES_SOLGALEO
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_SOLGALEO, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Lunala::
	lock
	bufferspeciesname 0, SPECIES_LUNALA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_LUNALA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Necrozma::
	lock
	bufferspeciesname 0, SPECIES_NECROZMA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_NECROZMA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Zacian::
	lock
	bufferspeciesname 0, SPECIES_ZACIAN
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ZACIAN, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Zamazenta::
	lock
	bufferspeciesname 0, SPECIES_ZAMAZENTA
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ZAMAZENTA, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Eternatus::
	lock
	bufferspeciesname 0, SPECIES_ETERNATUS
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_ETERNATUS, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Koraidon::
	lock
	bufferspeciesname 0, SPECIES_KORAIDON
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_KORAIDON, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Miraidon::
	lock
	bufferspeciesname 0, SPECIES_MIRAIDON
	msgbox LegendChalengeLobby_Text_PrepareToChallenge, MSGBOX_DEFAULT
	setwildbattle SPECIES_MIRAIDON, 80
	dowildbattle
	release
	end

LegendChallengeLobby_EventScripts_Terapagos::
	lock
	msgbox LegendChallengeLobby_Text_Terapagos, MSGBOX_SIGN
	release
	end

LegendChalengeLobby_Text_PrepareToChallenge:
	.string "You approach the LEGENDARY POKEMON\n"
	.string "known as {STR_VAR_1}.$"
	
LegendChallengeLobby_Text_Terapagos:
	.string "Terapagos isn't implemented yet.\p"
	.string "Sorry!$"
